server:
  port: 8081
  
spring:
  application:
    name: provider
  profiles:
    active: default
  config:
    import: configserver:http://localhost:8888
 
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka